sudo: false
language: node_js
node_js: "8"

git:
  depth: 3
  submodules: false

env:
  #matrix:
#    - NGV=current
#    - NGV=latest
#    - NGV=next
  global:
    - SAUCE_USERNAME=valorkin
    - SAUCE_ACCESS_KEY=aeaf806e-ad5c-484b-a8fe-4b4b9f54e99a

stages:
  - precache
  - lint
  - ci-test
  - build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
#  - npm install > /dev/null
  - if [[ "$NGV" == "latest" ]]; then  ./scripts/ci/npm-ng-latest.sh; fi
  - if [[ "$NGV" == "next" ]]; then  ./scripts/ci/npm-ng-next.sh; fi
  - npm run build > /dev/null
  - rm -rf node_modules/ngx-bootstrap
  - npm i ./dist  > /dev/null

#script: true

jobs:
#  exclude:
#    - env: NGV=current
  include:
  # precache
    - stage: precache
      install: true
      script: npm install > /dev/null
      addons:
        # sauce labs tunel connector (read more https://docs.travis-ci.com/user/sauce-connect/ )
#        sauce_connect: true
#        firefox: stable
        chrome: stable
        apt:
          sources:
          - ubuntu-toolchain-r-test
          # required by node-gyp to build some packages
          packages:
          - g++-4.8
#   lint code
    - stage: lint
      script: npm run lint
#   test
    - &ci-test
      stage: ci-test
      script: npm run test-coverage
      after_success:
        - ./node_modules/.bin/codecov
    - <<: *ci-test
      env: NGV=latest
      allow_failures: true
    - <<: *ci-test
      env: NGV=next
    - &build
    # check prod build
      stage: build
      script: npm run demo.ng-build
    - <<: *build
      env: NGV=latest
    - <<: *build
      env: NGV=next

cache:
  apt: true
  npm: true
  directories:
    - node_modules

before_cache:
 - rm -rf node_modules/ngx-bootstrap
