sudo: false
language: node_js
node_js: "8"

git:
  depth: 3
  submodules: false

env:
  global:
    - SAUCE_USERNAME=valorkin
    - SAUCE_ACCESS_KEY=aeaf806e-ad5c-484b-a8fe-4b4b9f54e99a

stages:
  - precache
  - lint
  - test
  - build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
# npm install will be done at precache stage
  - if [[ "$NGV" == "latest" ]]; then  ./scripts/ci/npm-ng-latest.sh; fi
  - if [[ "$NGV" == "next" ]]; then  ./scripts/ci/npm-ng-next.sh; fi

jobs:
  fast_finish: true
  allow_failures:
    - env: NGV=next
  include:
# precache npm and apt dependencies
    - stage: precache
      install: true
      script:
        - npm install > /dev/null
        - npm run build > /dev/null
        - rm -rf node_modules/ngx-bootstrap
        - npm i ./dist  > /dev/null
      addons:
       # sauce labs tunel connector (read more https://docs.travis-ci.com/user/sauce-connect/ )
#        sauce_connect: true
        chrome: stable
        apt:
          sources:
          - ubuntu-toolchain-r-test
          # required by node-gyp to build some packages
          packages:
          - g++-4.8
#   lint code
    - stage: lint
      install: true
      script: npm run lint
#   test
    - &test
      stage: test
      script: npm run test-coverage
      after_success:
        - ./node_modules/.bin/codecov
    - <<: *test
      env: NGV=latest
    - <<: *test
      env: NGV=next
#    check prod build
    - &build
      stage: build
      script: npm run demo.ng-build
    - <<: *build
      env: NGV=latest
    - <<: *build
      env: NGV=next
cache:
  apt: true
  npm: true
  directories:
    - node_modules

before_cache:
 - rm -rf node_modules/ngx-bootstrap
