sudo: false
language: node_js
node_js: "8"
dist: precise

git:
  depth: 3
  submodules: false

env:
  matrix:
    - NGV=current
    - NGV=latest
    - NGV=next
  global:
    - SAUCE_USERNAME=valorkin
    - SAUCE_ACCESS_KEY=aeaf806e-ad5c-484b-a8fe-4b4b9f54e99a

matrix:
  exlude:
    - stage: lint

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install > /dev/null
  - if [[ "$NGV" == "latest" ]]; then  ./scripts/ci/npm-ng-latest.sh; fi
  - if [[ "$NGV" == "next" ]]; then  ./scripts/ci/npm-ng-next.sh; fi
  - npm run build
  - rm -rf node_modules/ngx-bootstrap
  - npm i ./dist

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test-coverage
      after_success:
        - ./node_modules/.bin/codecov
    - stage: build
      script:
        - npm run demo.ng-build
#script:
#  - npm run lint
#  - npm run build
#  - rm -rf node_modules/ngx-bootstrap
#  - npm i ./dist
#  - npm run demo.ng-build
#  # istanbul is broken, should be fixed
#  - npm run test-coverage
#
#
#  #- npm run test-cross

cache:
  apt: true
  directories:
    - node_modules

before_cache:
 - rm -rf node_modules/ngx-bootstrap
 - rm -rf node_modules/@angular

addons:
  # sauce labs tunel connector (read more https://docs.travis-ci.com/user/sauce-connect/ )
  sauce_connect: true
  firefox: "latest"
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # required by node-gyp to build some packages
    packages:
    - g++-4.8
